// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrHPv9T3Ddw9-36e323SsLYhogAeksvo',
    appId: '1:287351475077:web:a19778a08f551f4a7ad2ec',
    messagingSenderId: '287351475077',
    projectId: 'fruit-store-d8c4e',
    authDomain: 'fruit-store-d8c4e.firebaseapp.com',
    storageBucket: 'fruit-store-d8c4e.firebasestorage.app',
    measurementId: 'G-YGDFVF4Y89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv04AmPqQbEmNd7EdoHYjCJ4nOyP0mkl0',
    appId: '1:287351475077:android:2c6e766d849949577ad2ec',
    messagingSenderId: '287351475077',
    projectId: 'fruit-store-d8c4e',
    storageBucket: 'fruit-store-d8c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Y_brSic4ZSGd0uiYER0-AFlu7rIcqJk',
    appId: '1:287351475077:ios:c62094262d5857817ad2ec',
    messagingSenderId: '287351475077',
    projectId: 'fruit-store-d8c4e',
    storageBucket: 'fruit-store-d8c4e.firebasestorage.app',
    iosBundleId: 'com.example.ntiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Y_brSic4ZSGd0uiYER0-AFlu7rIcqJk',
    appId: '1:287351475077:ios:c62094262d5857817ad2ec',
    messagingSenderId: '287351475077',
    projectId: 'fruit-store-d8c4e',
    storageBucket: 'fruit-store-d8c4e.firebasestorage.app',
    iosBundleId: 'com.example.ntiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaHI_ZcmVwnYhJd4F9Rp-ik9v6Kz0SGyU',
    appId: '1:287351475077:web:72d341c7a726f2577ad2ec',
    messagingSenderId: '287351475077',
    projectId: 'fruit-store-d8c4e',
    authDomain: 'fruit-store-d8c4e.firebaseapp.com',
    storageBucket: 'fruit-store-d8c4e.firebasestorage.app',
    measurementId: 'G-R00Y0NYH72',
  );
}
